# Generated by Django 5.2 on 2025-05-03 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('administrador', 'Administrador'), ('recepcionista', 'Recepcionista'), ('guiche', 'Guichê'), ('profissional_saude', 'Profissional de Saúde')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('funcoes', models.ManyToManyField(to='principal.funcao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='SenhaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_senha', models.CharField(choices=[('E', 'Exames'), ('C', 'Curativos'), ('P', 'Psicologia'), ('G', 'Geral'), ('D', 'Dentista'), ('A', 'Primeiro Atendimento'), ('NH', 'Hansenologia'), ('H', 'Hansenologia Retorno'), ('U', 'Ultrassom')], max_length=2)),
                ('numero', models.IntegerField()),
                ('senha_completa', models.CharField(max_length=5, unique=True)),
                ('nome_paciente', models.CharField(max_length=255)),
                ('horario_agendado', models.DateTimeField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('horario_registro', models.DateTimeField(auto_now_add=True)),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('chamada', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('guiche', models.ManyToManyField(related_name='tipos_atendimento_principal', to='atendimento.guiche')),
            ],
        ),
    ]
