# Generated by Django 5.2 on 2025-04-23 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('guiche', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('tipos_atendimento', models.ManyToManyField(blank=True, to='principal.tipoatendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.paciente')),
                ('senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='principal.senhapaciente')),
                ('guiche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.guiche')),
            ],
        ),
        migrations.CreateModel(
            name='SenhaChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=10)),
                ('data_hora_chamada', models.DateTimeField(auto_now_add=True)),
                ('guiche', models.CharField(max_length=10)),
                ('atendido', models.BooleanField(default=False)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.atendente')),
            ],
        ),
    ]
