# Generated by Django 5.2 on 2025-05-03 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0001_initial'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.paciente'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='senha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='principal.senhapaciente'),
        ),
        migrations.AddField(
            model_name='guiche',
            name='tipos_atendimento',
            field=models.ManyToManyField(blank=True, related_name='guiches', to='principal.tipoatendimento'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='guiche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.guiche'),
        ),
        migrations.AddField(
            model_name='senhachamada',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.atendente'),
        ),
    ]
