# Generated by Django 5.2 on 2025-05-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendente',
            name='nome',
        ),
    ]
